// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxCKBnc62wW8iucJQYjzlb3XBTGlgfsJo',
    appId: '1:147988034947:web:18eca9b05ca570e50772b6',
    messagingSenderId: '147988034947',
    projectId: 'celam-fb8f4',
    authDomain: 'celam-fb8f4.firebaseapp.com',
    storageBucket: 'celam-fb8f4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV2NrRjZbAONMBy8x6sU1tvcUyldoEX_Q',
    appId: '1:147988034947:android:e4bf5f98ea76b0970772b6',
    messagingSenderId: '147988034947',
    projectId: 'celam-fb8f4',
    storageBucket: 'celam-fb8f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw2lSBum8w5NADWnWlQcZ9x18YiBuTzc8',
    appId: '1:147988034947:ios:abae7764ee4cee620772b6',
    messagingSenderId: '147988034947',
    projectId: 'celam-fb8f4',
    storageBucket: 'celam-fb8f4.appspot.com',
    iosBundleId: 'com.example.celam',
  );
}
